### ISSUE TITLE
#11: Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by rnc0011** [rnc0011/GESPRO_Practicas#11]
Anexo de la memoria En Open shift En Local

**Comment by mni0000** [comment]
Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

**Comment by rnc0011** [comment]
Revisión de manual de usuario. Complementarla con la entregada en papel.

**Comment by mni0000** [comment]
Esta tarea ha sido resuelta en la issue #16 por considerar la creación de un apéndice adicional del el anexo, que incluya el despliegue de la instancia de SonarQube.
