### ISSUE TITLE
#12: Manual para escanear un Proyecto

### ISSUE THREAD

**Issue by rnc0011** [rnc0011/GESPRO_Practicas#13]
- Hablar de los ficheros de configuración dependiendo del lenguaje

- Comprobar la ejecución de Test Interesante

**Comment by mni0000** [comment]
Corregidos fallos en el manual de usuario en el que se explica como realizar análisis de proyectos con los distintos scanner de SonarQube

**Comment by rnc0011** [comment]
Adjunto revisión con comentarios pdf

**Comment by rnc0011** [comment]
He probado los manuales de usuario referentes a SonarQube Scanner y SonarQube Scanner for MSBuild y siguiendo sus pasos he conseguido escanear los proyectos de la primera convocatoria (PHP. Java y C#). He dejado los resultados en la instancia de SonnarQube.
Creo que es la mejor forma de probar la calidad de tu documentación ;-)
