### ISSUE TITLE
#2: Documentación sobre SonarQube

### ISSUE THREAD

**Issue by rnc0011** [rnc0011/GESPRO_Practicas#2]
Lectura de la documentación de la herramienta SonarQube, necesaria para poder realizar el despliegue y utilización de la misma.

**Comment by rnc0011** [comment]
Lectura de documentación adicional acerca de SonarQube en el libro G. Ann Campbell y Patroklos P. Papapetrou, "SonarQube in Action" (Manning).

**Comment by mni0000** [comment]
https://manning-content.s3.amazonaws.com/download/3/ca8fe47-b654-4956-b917-c997d8ec56a1/SQSampleCh01.pdf. 
La estructura del libro es buena y nos va a servir tanto para formalizar conceptos como para generar documentación de la memoria. Abarca distintas vistas de SonarQube dando respuesta a la justificación externa de su uso hasta cuestiones más internas de implementación como es la de desarrollar un plugin.

Entiendo que mucha información está directamente extraida de la página oficial de SonarQube pero tener una referencia bibliográfica da mayor consistencia a nuestro trabajo.

Buen trabajo
