### ISSUE TITLE
#19: Plugin información estadística de todos los proyectos

### ISSUE THREAD

**Issue by mni0000** [rnc0011/GESPRO_Practicas#20]
Tomar como ejemplo la evaluación en la página actual

Código ejemplo boxplot con JFreeChart

**Comment by rnc0011** [comment]
No se ha podido implementar un plugin que calcule información estadística de los proyectos debido a la falta de documentación del API de desarrollo de SonarQube. Sin embargo, esta tarea se ha resuelto de forma manual en la issue #23.
