### ISSUE TITLE
#4: Despliegue de instancia local de SonarQube

### ISSUE THREAD

**Issue by mni0000** [rnc0011/GESPRO_Practicas#4]
Despliegue de una instancia local de la herramienta SonarQube en la que se muestran los proyectos analizados. La instancia local es resultado de ejecutar una aplicación autónoma, sin necesidad de realizar ninguna instalación.

**Comment by rnc0011** [comment]
Requisitos para poder desplegar la instancia de SonarQube de forma local:

- Entorno de ejecución de Java (en mi caso Oracle JRE)

- Navegador Web para acceder al entorno de SonarQube (en mi caso Google Chrome)
