### ISSUE TITLE
#10: Documentación sección técnicas y herramientas

### ISSUE THREAD

**Issue by mni0000** [rnc0011/GESPRO_Practicas#7]
Indicar una visión general de la herramienta. Descripción funcional breve. Para qué se utiliza en la herramienta en el proyecto y referenciar a Web o libro.

SonarQube OpenShift

Jira Issues

Git IntelliJ Java LateX ....

**Comment by rnc0011** [comment]
Adjunto una versión provisional del apartado Técnicas y Herramientas de la memoria.

**Comment by mni0000** [comment]
Adjunto una revisión con comentarios sobre el pdf.
